"""
Safar AI — Report Download Service
Generates a downloadable HTML travel report (no email/Gmail needed).
"""

from utils.helpers import format_duration, format_cost


def build_downloadable_report(trip_info, best_route, report_text):
    """
    Build a professional HTML report for download.
    Returns HTML string.
    """
    cost_str = format_cost(best_route["cost"]["total_cost_pkr"]) if best_route else "N/A"
    eta_str = format_duration(best_route["eta"]["eta_min"]) if best_route else "N/A"
    safety = best_route["safety"]["score"] if best_route else "N/A"
    dist = best_route["distance_km"] if best_route else "N/A"

    # Convert markdown-ish report to basic HTML
    report_html = report_text.replace("\n", "<br>")

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Safar AI — Travel Report</title>
</head>
<body style="font-family:'Segoe UI',Arial,sans-serif;background:#0E1117;color:#FAFAFA;padding:20px;">
    <div style="max-width:650px;margin:0 auto;background:#1A1F2E;border-radius:16px;padding:30px;border:1px solid #2A2F3E;">
        <div style="text-align:center;margin-bottom:24px;">
            <h1 style="color:#00D4AA;margin:0;">🧭 Safar AI</h1>
            <p style="color:#90A4AE;margin:4px 0;">Smart Travel Report</p>
        </div>
        <div style="background:#0E1117;border-radius:12px;padding:20px;margin-bottom:20px;">
            <h2 style="color:#FFB74D;margin-top:0;">📍 {trip_info['origin']} → {trip_info['destination']}</h2>
            <table style="width:100%;color:#FAFAFA;">
                <tr><td>📏 Distance</td><td style="text-align:right;">{dist} km</td></tr>
                <tr><td>⏱️ ETA</td><td style="text-align:right;">{eta_str}</td></tr>
                <tr><td>🛡️ Safety</td><td style="text-align:right;">{safety}/100</td></tr>
                <tr><td>💰 Total Cost</td><td style="text-align:right;">{cost_str}</td></tr>
            </table>
        </div>
        <div style="line-height:1.7;">
            {report_html}
        </div>
        <hr style="border-color:#2A2F3E;margin:24px 0;">
        <p style="text-align:center;color:#90A4AE;font-size:12px;">
            Generated by Safar AI — Pakistan's Smart Route Predictor<br>
            Powered by Groq AI &amp; OpenRouteService
        </p>
    </div>
</body>
</html>"""
